[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = []
solc_version = "0.8.20"

# Enable optimizer with aggressive settings
via_ir = true
optimizer = true
optimizer_runs = 200  # Increase runs for maximum optimization

# Specify EVM version to target (e.g., Shanghai for better code generation)
evm_version = "prague"

# Detailed optimizer settings
[profile.default.optimizer_details]
constant_optimizer = true
yul = true
peephole = true
inliner = true
jumpdest_remover = true
order_literals = true
deduplicate = true
cse = true
yul_details = { optimize = true }

rpc_endpoints = { bscTestnet = "${BSC_TESTNET_RPC_URL}" }